### PR TITLE
Support Authelia bypass policies

### LINKED ISSUE #6: Support Authelia bypass policies
[Bypass policies](https://www.authelia.com/docs/configuration/access-control.html#bypass) don't currently work with this plugin, because Authelia returns empty `Remote-User` and `Remote-Groups` headers in the response, and the code currently errors if these are empty.

What's the reason for the error check? Seems like it's mostly a debugging convenience and could be removed to support this use case.

### PR DESCRIPTION
**Pull request by tpansino**
Resolves #6

### CODE REVIEW

**Comment by HeavenVolkoff** [comment]
So, while I do agree that the bypass functionality need to be supported, I don't think just removing the check for the returned headers is the best approach. Does authelia set any header informing that a bypass happened? If not, I would prefer checking that none of the header are filled, and then consider that a bypassed occurred. Also in that case I don't think setting the caddy variables to empty data would be desirable.

**Comment by tpansino** [comment]
> So, while I do agree that the bypass functionality need to be supported, I don't think just removing the check for the returned headers is the best approach.

What's the actual purpose of that check? It seems like it's just for debugging.

> Does authelia set any header informing that a bypass happened?

No, at least not in my testing. It makes sense though, forward auth is generally a dead-simple "I see a 2xx response, I allow" pattern. The `Remote` headers are only relevant for passing along user identity, which isn't possible in a bypass scenario because the user didn't authenticate.

> If not, I would prefer checking that none of the header are filled, and then consider that a bypassed occurred.

> that none of the header are filled

I'm not clear on what you mean.

The bypass response for my server looks like this:

```
HTTP/1.1 200 OK
Content-Length: 0
Date: Wed, 13 Apr 2022 04:51:48 GMT
Referrer-Policy: same-origin
Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Robots-Tag: none
X-Xss-Protection: 1; mode=block
```

Note that the `Remote` headers are not set, but note that the response status is 200. Are you saying we should check for exactly these two conditions, and consider that a bypass? But if any header is set and set to an empty string, error?

> Also in that case I don't think setting the caddy variables to empty data would be desirable.

Agreed, but that seems like then the `request_header` declarations in your example will raise an exception, no? (This is my first time working in Go, so I'm unclear how the language will behave here).

**Comment by tpansino** [comment]
I should mention - I checked the box for "Allow edits by maintainers". Feel free to make changes to my PR if that's easier/faster.

**Comment by HeavenVolkoff** [comment]
> Are you saying we should check for exactly these two conditions, and consider that a bypass?

Yeah, that is what I am proposing. It may seem unnecessary, but it is a very simple check that can avoid future undesired behavior that can arise from changes in authelia, and considering the nature of the service provided I prefer to err on the side of caution.

> Agreed, but that seems like then the request_header declarations in your example will raise an exception, no?

I never tested the behavior of accessing undefined placeholders in Caddy. If it is the case that no exception is raised, and caddy simply returns an empty value, I would prefer to not set the palceholders, and let caddy deal with it. However if it indeed raises an exception, then we set the variables to empty.

Do you think setting another variable indicating whether a bypass has occurred would be useful?

> I should mention - I checked the box for "Allow edits by maintainers". Feel free to make changes to my PR if that's easier/faster.

Thanks. Unfortunately I don't have much free time right now. But maybe in a few weeks I can work on this project more activitly again.

**Comment by tpansino** [comment]
I made some updates, let me know if this is better?

**Comment by tpansino** [comment]
I just did some more testing, and discovered that if either the user's email, name, or groups are not set in Authelia, then this check will fail, even though that's considered a valid user in Authelia.

I think the only required property is the username, so that's all we can test for this check. I've made the necessary updates.

**Comment by tpansino** [comment]
@HeavenVolkoff, awaiting your review. Let me know if you need more time.

(I'm not in a hurry, I just don't want to forget about it 😅 )

**Comment by gedw99** [comment]
Just chiming here … this caddy module looks great .

Is there any blockers here ?

**Comment by tpansino** [comment]
About two weeks after I opened this PR, the Caddy and Authelia devs teamed up and created a new Caddy directive called `forward_auth`, which is basically an officially-supported implementation of what this entire plugin does. As such, I think this project might be dead or moot.

See the [announcement](https://github.com/caddyserver/caddy/releases/tag/v2.5.1) or the [docs](https://caddyserver.com/docs/caddyfile/directives/forward_auth#authelia) for the new directive for more details.

**Comment by HeavenVolkoff** [comment]
Hey @tpansino, sorry for not getting back to you and finishing reviewing this PR. It slipped my mind. For some time now, I stopped using Authelia as I changed a lot of the backend I was running it on, and it became redundant. It's good to know that there is now an officially supported method for using external authentication with Caddy. I will update the README and archive this repo then. Thank you.

**Pull request closed without merging**
